apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: hw3-postgres-pgadmin
spec:
  type: LoadBalancer
  selector:
    app: pgadmin
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      # nodePort: 30500
